NUM_CHANS=1 # numbers of channels
NUM_PFQS=1
DDR_TYPE="hbm3" # lpddr4, lpddr5, lpddr6, guardians-d1, guardians-d2, guardians-3d, ddr5, ddr4, hbm2e, hbm3
DDR_MODE="" # ddr5/ddr4: _x16/_x4, guardians-3D: _4sub/_8sub/_4sub_m/_8sub_m
DMC_RATE=9600 # data rate for lpddr
DRAM_VENDOR="ss" # ss(samsumg), sk(hynix), mc(micron), cx(changxin), bb(bluebird), rm(ring memory)
DRAM_MODE="" # suffix for dram power ini
# TRANS_QUEUE_DEPTH=64 # transaction queue, CPU-level commands
# TABLE_DEPTH=0 # DMC table number, 0: unlimited, others: limited
EXEC_NUMBER=2 # exec number
RD_APRE_EN=true # read auto precharge
WR_APRE_EN=true # write auto precharge
ENHAN_RD_AP_EN=false # read auto precharge with no rowhit, page timeout with bank has no cmd
ENHAN_WR_AP_EN=false # write auto precharge with no rowhit, page timeout with bank has no cmd
AREF_EN=true
PBR_EN=true
ENH_PBR_EN=false
ENH_PBR_CEIL_EN=false   # true: ceil efficiency under enhanced pbr(1in24); false: 4in1 && 6in1
DERATING_EN=false # switch for reload timing under high tmp; 
DERATING_RATIO=1 # refresh ration under different temp, 1 -> 1x; 2->2x; 4-> 4x; 
PBR_PARA_EN=false # switch for parallel perbank refresh, only for lp5/lp6; 
AREF_OFFSET_EN=false # use offset for aref/pbr
SBR_IDLE_EN=true # Idle rank send pbr
SBR_REQ_MODE=1 # 0 is refresh Idle bank priority, otherwise refresh work bank, 1 is force refresh if left n banksquit
SBR_FRCST_NUM=16 # refresh the left banks if refreshed bank reach this number
SBR_WEIGHT_MODE=0 # send pbr weight mode, 0 is check bank pairs open bank number, 1 is check bank pairs bank number with command in, 2 is mode0 + mode1, 3 is 1 + mode2 * 2
SBR_WEIGHT_ENH_MODE=0 # some extra sel conditions Apart from SBR_WEIGHT_MODE, 0 is no extra conditions, 1 is keep bank pair group complete(only used for ebnhanced pbr) , 2 is most recently scheduled banks as refresh bank pair
SBR_GAP_CNT=0 # rank sbr send gap
SBR_IDLE_ADAPT_EN=false
SBR_IDLE_ADAPT_WIN=4000 # ns, 4us
SBR_IDLE_ADAPT_LEVEL=40 # great than this will send pbr, else send abr
# SEND_DSTREF_SERIAL=true # GD2 send dist refresh serially follow by rtl, or follow spec
ABR_PSTPND_LEVEL=7 # all bank refresh postponed level
PBR_PSTPND_LEVEL=5 # per bank refresh postponed level
PRE_PBR_PSTPND_LEVEL=4 # pre per bank refresh postponed level
PD_PBR_EN=true # send pbr in pd state
# FG_REFRESH_TH=8
FASTWAKEUP_EN=false # sysarch will follow top config, others false
PREDICT_FASTWAKEUP=false # predict fastwakeup
# QOS_INV=true # System QOS convert to DMC QOS
# GREEN_PATH_DIS=false # true: qos + 1 to disable green path
# TIMEOUT_ENABLE=false
TIMEOUT_PRI_RD=[256,1024,1536,2048,3072,3072,3072] # qos1->qos7
TIMEOUT_PRI_WR=[256,1024,1536,2048,3072,3072,3072] # qos1->qos7
# PRI_ADPT_ENABLE=false
ADAPT_PRI_RD=[0,48,48,48,48,48,48] # qos1->qos7
ADAPT_PRI_WR=[0,48,48,48,48,48,48] # qos1->qos7
MPAM_MAPPING_TIMEOUT=false
MPAM_TIMEOUT_RD=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # mpam0->mpam15
MPAM_TIMEOUT_WR=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # mpam0->mpam15
MPAM_ADAPT_RD=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # mpam0->mpam15
MPAM_ADAPT_WR=[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0] # mpam0->mpam15
PRIORITY_PASS_ENABLE=true
QOS_POLICY=1 # qos policy, for qos1 and qos2 policy
RDATA_TYPE=0 # Return Rdata type, 0: first DDR CMD, 1: last DDR CMD
PAGE_ADAPT_EN=false # for new page adapt policy
PAGE_TIMEOUT_EN=true
OPENPAGE_TIME_RD=114 # UT is fixed 114 in all frequency point
OPENPAGE_TIME_WR=114 # UT is fixed 114 in all frequency point
ENH_PAGE_ADPT_EN=false # enhance page adapt policy enable
ENH_PAGE_ADPT_WIN=1024 # enhance page adapt policy capture window
ENH_PAGE_ADPT_LVL=[3,5,20] # bank command number in capture window, [6,10,20] for better power
ENH_PAGE_ADPT_TIME=[0,48,64,128] # dfi cycle, [0,64,96,128] for better power
DMC_BW_WIN=1024
DMC_BW_LEVEL=[25,50,75] # feedback bandwidth level
PAGE_ADPT_EN=false # for rtl page adapt policy
PAGE_WIN_MODE=0 # 0: just opc/ppc command, 1: all command
PAGE_WIN_SIZE=48 # page adapt win size
PAGE_OPC_TH=32 # opc threshold
PAGE_PPC_TH=16 # ppc threshold
PAGE_ADPT_STEP=4 # openpage_time add/dec step
PAGE_TIME_MAX=8192 # openpage_time max value
DRESP_BP_TH=6 # threshold of dresp backpress
BUSYSTATE_INC_WCMD=false
BUSYSTATE_TH=32
IECC_ENABLE=false
PDU_DEPTH=64
IECC_CONFLICT_CNT=4
IECC_PARTIAL_BYPASS=false
IECC_BYPASS_ADDRESS=0x10000000 # great than this address will bypass IECC
IECC_BL32_MODE=false
IECC_PRI=7 # Ecc code command pri
IECC_CAP_RATIO=960
DMC_THEORY_BW=11 # for 5.5GHz
FLOW_STAT_TIME=512000 # 512~512K dmc cycles
MPAM_PUSH_EN=false
MID_PUSH_EN=false
PD_ENABLE=true
PD_PRD=100 # ns, 100ns
ASREF_ENABLE=true
ASREF_PRD=10000 # ns, 10us
ASREF_ADAPT_EN=false
ASREF_ADAPT_WIN=10000 # ns, 10us
ASREF_ADAPT_LEVEL=[2,4,40]
ASREF_ADAPT_PRD=[4000,5000,7000,8000] # ns
# BG_ROTATE_EN=false # bank group rotate enable
# RCMD_BANK_ARB_EN=false # Balanced scheduling of bank command
# WCMD_BANK_ARB_EN=false # Balanced scheduling of bank command
# RCMD_BANK_ARB_PRI=3 # Rcmd bank balanced level
# WCMD_BANK_ARB_PRI=4 # Wcmd bank balanced level
WCK_ALWAYS_ON=false # wck always on
CAS_FS_EN=false # CAS_FS command for improve performance with rank switch
CAS_FS_TH=8 # other rank cmd cnt which less equal than this threshold will triger send CAS_FS
CORE_CONCURR=2 # dual transmitting number, 0 is illegal
CORE_CONCURR_PRD=1 # dual transmitting period
# GRP_RW_EN=true # rw group enable
# ENGRP_LEVEL=4 # enter rw group command level
# EXGRP_LEVEL=2 # exit rw group command level
# CMD_WLEVELL=16 # write command low level in transactionQueue
# CMD_WLEVELH=32 # write command high level in transactionQueue
# SERIAL_RLEVELL=0 # read low level in read group
# SERIAL_RLEVELH=96 # read high level in read group
# SERIAL_WLEVELL=0 # write low level in write group
# SERIAL_WLEVELH=96 # write high level in write group
# RLEVEL_R2W=24 # read command group level
# ALEVEL_W2R=5 # just for hbm, w2r level 
# HARDWARE_RHIT_EN=false # hardware automatic identification rhit ratio
# CMD_RLEVELL=2 # read command low level in transactionQueue
# CMD_RLEVELH=4 # read command high level in transactionQueue
# RHIT_RW_CMD_NUM=200 # read and write command number
# RHIT_ACT_CMD_NUM=76 # active command number
RWGRP_TRANS_BY_TOUT=false # rw group transition by timeout command
# RWGRP_AUTO_BW=1000 # availability ge this value will be allowed exit rw group
# GRP_RANK_EN=false # rank group enable
GRP_RANK_MODE=0 # 0: use DMC command cnt, 1: use DDR max BL command cnt
# GRP_RANK_PREPB=false # the bank in other rank will be precharged(PB) in rank group mode
# GRP_RANK_PREAB=false # the bank in other rank will be precharged(AB) in rank group mode
# GRP_RANK_LEVEL=0 # current rank_cnt ge this value will allow other rank send precharge
# SIMPLE_GRP_RANK_EN=false # simple rank group enable
# READ_RANK_GRP_LEVEL0_H=6
# READ_RANK_GRP_LEVEL0_L=4
# READ_RANK_GRP_LEVEL1_H=10
# READ_RANK_GRP_LEVEL1_L=8
SIMPLE_GRP_SID_EN=false # simple sid group enable, for hbm3
# GRP_SID_LEVEL=[12,10] # simple sid group level
# RCMD_HQOS_EN=false # high qos read timeout command effective immediately
# RCMD_HQOS_LEVEL=2 # command pri less equal than this value means high qos command
# SWITCH_HQOS_LEVEL=2 # command which qos is less equal than this value means high qos command
CPU_MID_START=46 # range of cpu mid
CPU_MID_END=62 # range of cpu mid
# RCMD_HQOS_W2R_SWITCH_EN=false # high qos read commands trigger group switching
# RCMD_HQOS_W2R_RLEVELH=4 # high qos read command number in transactionQueue
# RCMD_HQOS_RANK_SWITCH_EN=false # rank group enable
# RCMD_HQOS_RANK_SWITCH_LEVELH=4 # high qos read command high level in transactionQueue
# RCMD_HQOS_RANK_SWITCH_LEVELL=2 # high qos read command low level in transactionQueue
# RCMD_HQOS_RANK_SWITCH_ROWHIT_LEVEL=2 # rank rhit num level in transactionQueue
RHIT_HQOS_BREAK_EN=false # high qos rowhit break enable
RHIT_HQOS_BREAK_OTH_RCMD_LEVEL=1 # high qos rowhit break level
# RHIT_BREAK_EN=true
# RHIT_BREAK_LEVEL=8
# RW_GRPCHG_W2R_TH=16 # write grp change to read group threshold
# RW_GRPCHG_R2W_TH=16 # read grp change to write group threshold
DMC_V580=true
DMC_V590=true
DMC_V596=false
# EARLY_TCCDL_EN=false # use early tccd_l in un bg interleave mode
TRFC_CC_EN=false
# WB_WDEPTH=128
# WB_RDEPTH=32
MERGE_ENABLE=false
FORWARD_ENABLE=false
# DYN_BYP_EN=true # Gbuf read bypass enable
# GBUF_RCMD_BLOCK_PBR=false # Read cmd in Gbuf will block the bank to send pbr
# GBUF_RD_BRK_WFLUSH_CMD=false # rd break wr by rd command
# GBUF_RCMD_TIMEOUT=1024 # for all read cmd, 0 is timeout disable
# GBUF_WCMD_PRIADAPT=1048576 # 2 ^ 20, 0 is timeout disable
# RQ_RNKCONF_EN=true # send excuting rank cmd priority
RQ_ADCONF_PUSH_EN=true # same address rcmd push wcmd pri
CMD_ROW_ORDER=0 # rd order config, 0: normal order, 1: row order include dmc order, 2: no use, 3: row order only gbuf
TOTAL_RCMD_MODE=0 # 0: dmc rd + rq, 1: rq, 2 dmc rd
# RQ_BACONF_MODE=0 # 0: rd + wr, 1: rd, 2 wr
# WQ_BACONF_MODE=0 # 0: rd + wr, 1: rd, 2 wr
RO_HIT_EN=false # wr cmd rowhit high priority
GRP_MODE_LEVEL0=[0,0,0,0,0] # bw0, 7: write bank conf with DMCQ write cmd, 6: read push write's priority
GRP_MODE_LEVEL1=[0,0,0,0,0] # bw1, 5: rank switch mode, 4: read group enable, 3~2: BG conf threshold
GRP_MODE_LEVEL2=[0,0,0,0,15] # bw2, 1: BA conf with DMC or DMC + RQUE
GRP_MODE_LEVEL3=[0,0,6,6,31] # bw3, 0: BA conf cannot set req
BANK_CMD_TH=[0,0,0,0,0] # great than this value will not send command to dmc
NO_CMD_SCH_TH=[12,31,31,31,31]
# WGRP_RANK_MODE=[1,1,1,1,1] # 5 level, 0: sch max rank only, 1: sch max rank priority, 2: dont distinguish rank
# WR_LEVEL0=[13,28,35,38,48]
# WR_LEVEL1=[13,28,33,35,48]
# WR_LEVEL2=[13,28,33,35,48]
# WR_LEVEL3=[13,28,33,35,48]
# WR_MOST_LEVEL0=[10,13,15,25,45]
# WR_MOST_LEVEL1=[10,13,15,28,40]
# WR_MOST_LEVEL2=[10,13,15,28,43]
# WR_MOST_LEVEL3=[10,13,15,28,43]
# RD_LEVEL0=[1,3,4,8,33]
# RD_LEVEL1=[1,3,4,8,25]
# RD_LEVEL2=[1,3,4,8,25]
# RD_LEVEL3=[1,3,4,8,25]
WR_LEVEL0=[24,28,32,36,42]
WR_LEVEL1=[24,28,32,36,42]
WR_LEVEL2=[24,28,32,36,42]
WR_LEVEL3=[24,28,32,36,42]
WR_MOST_LEVEL0=[16,24,36,48,72]
WR_MOST_LEVEL1=[16,24,36,48,72]
WR_MOST_LEVEL2=[16,24,36,48,72]
WR_MOST_LEVEL3=[16,24,36,48,72]
RD_LEVEL0=[4,8,14,20,26]
RD_LEVEL1=[4,8,14,20,26]
RD_LEVEL2=[4,8,14,20,26]
RD_LEVEL3=[4,8,14,20,26]
PERF_ENGRP_LEVEL=5
PERF_EXGRP_LEVEL=3
PERF_CMD_WLEVELH=40
WRITE_BUFFER_ENABLE=true
BS_BP_LVL=6
BANK_SLOT_NUM=48
WDDA=35
WSRAM_QUEUE_DEPTH=584
WSRAM_QUEUE_WIDTH=32
WSRAM_MAP_EN=true
BSC_EN=false
EM_ENABLE=false # efficiency mode
EM_MODE=0 # 0: dynamic efficiency mode; 1: static efficiency mode; 2: combo efficiency mode
RMW_ENABLE=false
RMW_ENABLE_PERF=false
RMW_CMD_MODE=0 # 0-> fast command mode; 1-> non fast command mode
RMW_QUE_DEPTH=0 # 0-> unlimited; others: limited 
RMW_CONF_SIZE=64 # granularity of address conflict judge, eg: 32:32B; 64:64B; 128:128B 
# GRT_FIFO_DEPTH=16 # grant fifo depth in rtl DISPATCH
# TRANS_FIFO_DEPTH=4 # trans fifo depth in rtl TRANS
ROW_SEL=15 # swap bit of row address with sc address under combo e-mode
CONF_EN=false   # conflict check of PTC queue
# SIMPLE_RWGRP_EN=false # simple rw group in PTC
# SIMPLE_RWGRP_MODE=0 # 0: rd_wr seperate mode; 1: up to ptc order(combined with SLOT_FIFO=true); 2: up to perf_grpst_switch_cnt; 3: up to ptc availability
PERF_GRPST_SWITCH_LVL0=1
PERF_GRPST_SWITCH_LVL1=2
SIMPLE_RNKGRP_EN=false # simple rank group in PTC
ARB_GROUP_NUM=4 # Group number of PTC queue
ACT_LEFT_CYCLE=6 # cycle number to send act
# MAXCNT_SAMEBG = 2 # upper limit of same bg cmd cnt in PTC
PTC_RANK_NUM = 2 # allowed number of rank in PTC
PTC_TIMEOUT_ENABLE=true
PTC_TIMEOUT_MODE = 1 # 0: same as v700; 1: backpress diff_rank && diff_type cmd
PTC_TIMEOUT_PRI_RD=[512,256,128] # qos0->qos2
PTC_TIMEOUT_PRI_WR=[512,256,128] # qos0->qos2
PTC_PRI_ADPT_ENABLE=true
PTC_ADAPT_PRI_RD=[48,48,48] # qos0->qos2
PTC_ADAPT_PRI_WR=[48,48,48] # qos0->qos2
PTC_QOS_MAX = 7
PTC_ADAPT_PRI_MAX = 4
PERF_PRE_EN=true
PTC_SEARCH_EN=false
# PTC_BANK_BAL_EN=false
TRANS_QUEUE_DEPTH=16 # transaction queue, CPU-level commands
PERF_RD_RELEASE_MODE=0 # 0 means release perf until ptc schedule; 1 means release perf until data received
PTC_BYP_UPDATE_EN=true  # true: update perf_rowhit/perf_rowmiss directly by bypath path; false update perf_rowhit/perf_rowmiss up to rw group in PERF
EXEC_UNLIMIT_EN=true    # unlimited exex source
PBR_LESS_CMD_EN=false
PBR_LESS_CMD_MODE=1 # 0: used for PBR_LOCK_MODE=0(rw_switch); 1: used for PBR_LOCK_MODE=1(sel 1 bank -> bp bank pairs)
PBR_LESS_CMD_LEVEL=0
PBR_LOCK_MODE=0 # 0: depend on both of bank pairs; 1: depend on one of bank pairs, bounded with PBR_LESS_CMD_EN=true
PBR_SEL_MODE=0 # 0: depend on cmd of ptc; 1: depend on cmd of perf
PTC_RANK_SWITCH_EN=false
PTC_RRANK_SWITCH_LEVEL=6
PTC_WRANK_SWITCH_LEVEL=4
PTC_RSCH_GAP_CNT = 8
PTC_WSCH_GAP_CNT = 16
PTC_QOS_HOLD_EN = true
# PTC_WR_MERGE_EN=false
# PTC_RD_MERGE_EN=false
PTC_HQOS_RANK_SWITCH_EN = true
PTC_HQOS_RANK_SWITCH_MODE = 3  # 0: hqos rank timeout mode; 1: hqos rank switch mode(bp rwcmd); 2: hqos rank switch mode(bp rcmd) 
PTC_HQOS_RANK_SWITCH_LEVEL1 = 0 # 0: ignore level; other: less than level
LP_WAKEUP_MODE=0 # 0: wakeup lp state with perf cmd; 1: wakeup lp state with ptc cmd; 2: wakeup lp state with perf rd cmd
FAST_READ_EN=true # fast read command mode
FAST_READ_MODE=1 # 0: active mode; 1: full command mode
FAST_RD_CANCEL_EN = true # true: cancel fast rd with ad_conf; false: not cancel  
FAST_RD_CANCEL_MODE = 1 # 0: fast read only up to perf rd; 1: fast read up to perf rd/wr 
BYP_ACT_EN=true  # bypass active in ptc
BYP_ACT_PIPE3_EN=false  # bypass active pipeline add 1 cycle
# FAST_HQOS_TOUT_EN = false  # fast hqos read cmd labled with timeout
FAST_HQOS_PUSH_EN = true  # hqos read cmd push cmd in ptc
FAST_HQOS_PUSH_MODE = 3  # 0: improve to second highest; 1: label with timeout; 2: improve to second highest && label with timeout possibly  
PTC_EMPTY_RD_TH = 18
PTC_EMPTY_WR_TH = 18
PTC_R2W_SWITCH_TH = 10
PTC_W2R_SWITCH_TH = 10
PTC_RHIT_BREAK_EN = true
PTC_RHIT_BREAK_LEVEL = 8
TOUT_SCH_TIME = 300

PERF_CLK_MODE = 1
RDATA_RETURN_NUM = 1
PERF_DEPTH = 64
PERF_SUBQ_NUM = 4
SUBQ_SEL_MODE = 1
PERF_RELEASE_REC_WIN = 0
CLKH2CLKL = 2
PERF_PRI_ADAPT_ENABLE = true 
PERF_QOS_POLICY = 2 # 0 : unvalid; 1: perf qos policy1; 2: perf qos policy2
QOS_MAX = 7
PERF_ADAPT_PRI_MAX = 4
PTC_MAX_RANK = 2
PTC_MAX_CNT_PER_RANK = 8
SAME_BANK_CNT_RD = 2
SAME_BANK_CNT_WR = 2
SAME_BANK_CNT_ROWMISS = 1
PERF_ROWHIT_BREAK_TH = 20
SAME_BG_CNT_RD = 0
SAME_BG_CNT_WR = 0
BG_PRE_N_CMD = 1
PERF_TIMEOUT_EN=true
PERF_TIMEOUT_MODE = 1 # 0: perf && ptc timeout seperatly; 1: perf && ptc timeout combined
TOUT_FORCE_RWGRP_EN = false  # true: timeout force rwgrp switch; false : timeout not related to rwgrp
PERF_DUMMY_TOUT_EN = true
PERF_TIMEOUT_PRI_RD=[6144,4096,4096,6144,2600,2048,512] # qos0->qos6
PERF_TIMEOUT_PRI_WR=[4096,4096,4096,3072,2600,2048,512] # qos0->qos6
PERF_ADAPT_PRI_RD=[384,384,384,384,384,384,384] # qos0->qos6
#PERF_ADAPT_PRI_WR=[384,384,384,384,384,384,384] # qos0->qos6
#PERF_ADAPT_PRI_WR=[1024,1024,1024,1024,1024,1024,384] # qos0->qos6
PERF_ADAPT_PRI_WR=[4096,4096,4096,4096,2048,2048,1024] # qos0->qos6
# PERF_RHIT_BREAK_EN=false
IDLE_TRIG_TIME=32
GAP_CNT_BASE=1 # 4*GAP_CNT_BASE
GAP_CNT_TIMES=0 #pow(2,GAP_CNT_TIMES)
RANK_GROUP_MODE=2
# PERF_RANK_CTRL_EN=false
# PERF_MAXBG_PUSH_PRI_EN=false
# PERF_MAXBANK_PUSH_PRI_EN=false
# PERF_PUSH_PRI_TH=4
# FORCE_WCMD_SCH_EN=false
PERF_ACT_TCHK_EN=true
# PERF_WR_MERGE_EN=false
# PERF_RD_MERGE_EN=false
PERF_RANK_WMERGE_EN=true
PERF_RANK_RMERGE_EN=true
PERF_READ_SCH_THH=7
PERF_READ_SCH_THL=7
PERF_WRITE_SCH_THH=7
PERF_WRITE_SCH_THL=7
PERF_SCH_RRANK_LEVELH=6
PERF_SCH_RRANK_LEVELL=2
PERF_HOLD_RRANK_LEVELH=6
PERF_HOLD_RRANK_LEVELL=2
PERF_SCH_WRANK_LEVELH=4
PERF_SCH_WRANK_LEVELL=2
PERF_HOLD_WRANK_LEVELH=4
PERF_HOLD_WRANK_LEVELL=2
PERF_RRNK_ENGRP_LEVEL=8
PERF_RRNK_EXGRP_LEVEL=4
PERF_WRNK_ENGRP_LEVEL=8
PERF_WRNK_EXGRP_LEVEL=4
# PERF_BG_BAL_EN=false
# PERF_BANK_BAL_EN=false
# PERF_SLOT_TRANS_EN=false
PERF_RWGRP_MODE=0 # 0: default perf rw group; 1: dmc rw group
PERF_STATE_PRI_EN = false
PERF_RHIT_PRI_EN = false
PERF_RANK_PRI_EN = false
# PERF_HOLD_FIFO_EN = false  # keep FIFO
# PERF_HOLD_FIFO_MODE = 0  # 0: adapt cmd pri according to followed cmd num; 1: tbd
# PERF_HOLD_FIFO_TH = 64
PERF_ADCONF_R2W_EN = false
PERF_FAST_R2W_EN= false
# PERF_RCMD_HQOS_DUMMY_EN = false  # high qos read commands trigger high qos dummy
PERF_RCMD_HQOS_DUMMY_LEVEL = 1  # high qos read commands level in perf queue
PERF_RCMD_HQOS_W2R_SWITCH_EN = true # high qos read commands trigger group switching 
PERF_RCMD_HQOS_W2R_RLEVELH = 1 # high qos read command number in perf queue 
PERF_SWITCH_HQOS_LEVEL = 5 # command which qos is higher or equal than this value means high qos command 
# PERF_RCMD_HQOS_RANK_SWITCH_EN = false # rank group enable
PERF_RCMD_HQOS_RANK_SWITCH_LEVELH = 1 # {2} high qos read command high level in perf queue
PERF_RCMD_HQOS_RANK_SWITCH_LEVELL = 1 # {1} high qos read command low level in perf queue
# RCMD_HQOS_RANK_SWITCH_ROWHIT_LEVEL=2 {1} # rank rhit num level in transactionQueue
PERF_NG_HOLD_WR_EN = false
PERF_NG_HOLD_WR_MODE = 0  
PERF_NG_HOLD_WR_CNT = 48
RPFIFO_EN=false
RPFIFO_DEPTH=50
RPFIFO_AMFULL_TH=8
RMW_RDATA_FIFO_DEPTH = 4
ODD_TDM=true
SIMPLE_BANKTABLE_ENABLE=false
PREACT_FLOW_CTRL_EN=true
PREACT_FLOW_CTRL_TYPE=0
PREACT_BW_THD=100
PREACT_TBL_THD=32
SID_LOOSE=false
TIMEOUT_SID=1024
TIMEOUT_SID_ENABLE=false
SERIAL_PRE_SIDGRP=8
ENGRP_LR_LEVEL=32 
EX_LR_LEVEL=16
LR_LEVELH=24 # need less than cmd_rlevelh?
LR_LEVELL=16
SERIAL_LR_LEVELH=40
SERIAL_LR_LEVELL=12
SID_GRP_PIPE=1
ROW_SEL_MSB=14
ROW_SEL_SMSB=13
ADDR_EXP_EN=true